uploads = []

[[generated]]
id = "-8kGVTR6i-UNvvRzLNGB-"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "yhSeerbDLljJPU6jiFCGh"
uri = "file://ios_dist_csr.zip"
type = "unspecified"
title = "iOS Certificate Signing Request (.certSigningRequest inside)"

[[outputs]]
id = "ZIToo-pO4wsBGpmuRVKS1"
uri = "file://android_keystore.zip"
type = "unspecified"
title = "Android Keystore (android.p12 inside)"

[[outputs]]
id = "TT2mWlhkzngCzjrkkKYvU"
uri = "file://ios_csr.zip"
type = "unspecified"
title = "iOS CSR — unzip and upload to Apple Developer Portal"
